### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by reeshabhranjan** [ignazio1977/owlexplanation#3]
@ignazio1977 I am getting a Null Pointer Exception when trying to generate explanations. The [code](https://github.com/ignazio1977/owlexplanation/commit/924dee90ddab6811abf3a4bb44d9c6df997779f1) which fixes this issue probably isn't present in the version 5.0.0 of the dependency available in Maven repository.

**Comment by ignazio1977** [comment]
Indeed. I'll release 5.0.1.

**Comment by ignazio1977** [comment]
Released. Will be on Maven Central soon.
